travis:
  secure:
    BINSTAR_TOKEN: AT6+uuR1TB9oirYa1OiKihonCzMKBEUW9jB4USkbqeZuryNv/X/Y3r598hVhTYoT0f6oG2Cw+0l/16a75Ex8q2Q4DvTPeTCCQL8uIurtIvOp+Swas9FTs6ZbvAkKgAEGsSVzAawkuuiKfyVnerUi1L34vB8DwoiCwrFRltEYQ4wooEnBfArFK+w8FSMzKIM8rVpqrFENE/DyxWASUdSbZKd+IkoXspXH9jp9YkspUymyS+nW30XSvx/CGaLdULnCw9OBN/U6J5nojWPormevrnBTQjm1faZGsbxA70CgWlYSBIi7c8KpiDO10L52LpsLvpsdTtY7z/n+/hA7KL6qzmR5Nx11h1z8l/xQTD6RHs5/j/c8cjqrcDWsVlTpHOPTqQlNMQG76ahAGOQodocY1A91Qxl3ITNkIYkPL/Ff9yqd4nZ6OcrU5a+A/C3oJ1uqkMr6dixqk1FfVTPTWGwNOvPVdkMygAzdi5OM8ZdkfjWKkF43sCtE/fBbg1juabZ7z9lt8JjJ9pR8vB96+Fl5tkfsDZ4rbk2R4owid8tsvFTNwVony3YS5P1KJVobOHMfbhq8+bbD6ZfYzw4b0U9AVoWpwjcqtSd/cuIohVENhK28iyc/oG8tsDQOQt8W2X+SCYl2QM7BqPGiV28zgN9uA//TmqfvrSGjwUzVHfQ+ilU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
