travis:
  secure:
    BINSTAR_TOKEN: QnSnlNN3kwv5OFxg7NpUFqo3nDCqG+e5RfsulDLG3px6Ai+sJxTZwNrTXWq+z5lgrpSDg/sBJNJdsvEDXGX2OnyRBWsFdq/X4EuHWRcM+9q0o1tBk8rxLdLFT4EezutwZjMi4heA/hix6epckrsPqpQeFu3oD1RVjEH5IYN06RHcXdVn5xZMBbjAsBnS3v+b0tE/NCqxE2bdkrjqz7efoevgGt9zfRdDtMuEbjfZbIBbj2KfUcYMPKPm5JFfxPCo6w39JdwaRqgX3wDEkC0seKbEGTuiqc/tFRf4jkYzxyOnPiPnKxumuhVSaqNEwkXeosww7g6MZNQsCr1lmIEiEIDi8CQdLcRer0SJP7Mo1YUIyr9588L5Og14TaL0DWHMeYCrCE7QUxM2U+6b2CAze5FAZA0eDdeCc/5G7OAQ4F1+UmLqc24XOn4nwNg0rXFL6+3lnA0Su0GkX2TVRe9f2Omu3uHit9U9i6MzH7lDeAdRSsgUFCgCo+YkwPOM2oiAjk+TeT7tmhyzPLPJjMYl4BlsM7O30aoTK5+Ubr073pviOgIxHOq42ADQBdV8JE067zyfeIK5Pq19uJBMC9N2ggqYi8ybj4su4RrmFARO7wWp9ZXpGhnhy+8Jcw97516+c8sydoKuCSGoVXeJAzP70YYh5tmmwdaNUC4pd7uvWoo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
